services:
  physiquest_animation_generator:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/physiquest_animation_generator:cashed
    command: ["tail", "-f", "/dev/null"]

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Physiquest
      POSTGRES_PASSWORD: genereater
      POSTGRES_DB: physiquest_animation_generator

volumes:
  postgres_data:
